sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t ricardogj/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ricardogj/docker-react npm run test -- --coverage